# Generated by Django 4.2.4 on 2023-09-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telling_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='pattern',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
