# Generated by Django 4.2.4 on 2023-09-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telling_app', '0002_questions_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='user',
        ),
    ]
